service: hello

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters
  - serverless-plugin-monorepo
  - serverless-domain-manager
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ap-south-1

functions:
  hello:
    handler: handlers/hello.handler
    events:
      - http:
          method: GET
          path: /

custom:
  base: ${file(../../packages/serverless/Base.yml)}
  domains: ${self:custom.base.domains}
  customDomain: ${self:custom.base.customDomain}
  bundle:
    disableForkTsChecker: true
